In [23]:
# Create a model that predicts profit of company based on spending pattern and company's location
# SL = 0.1
# Deploy model once created

In [24]:
import pandas as pd
import numpy as np

data = pd.read_csv("50_Startups.csv")
data.head(5)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [26]:
# There are no null values present in the features

In [27]:
#Seperate data as features and label
features = data.iloc[:,[0,1,2,3]].values
label = data.iloc[:,[4]].values

In [28]:
# Since, categorical feature is present, let us do OHE (One Hot Encoding)

In [29]:
from sklearn.preprocessing import OneHotEncoder

In [30]:
oheState = OneHotEncoder(sparse_output=False)
stateDummy = oheState.fit_transform(data.iloc[:, [3]])

In [31]:
oheState.categories_

[array(['California', 'Florida', 'New York'], dtype=object)]

In [32]:
stateDummy

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0

In [33]:
# concatenate the encoded state with the original dataframe

In [34]:
finalFeatureSet = np.concatenate((stateDummy,features[:,[0,1,2]]) , axis = 1)
finalFeatureSet

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

In [35]:
# Model exploration phase

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

CL = 0.9

best_test_score = -1
best_rs = -1

for rs in range(1, 101):
  X_train, X_test, y_train, y_test = train_test_split(finalFeatureSet, label, test_size=0.2, random_state=rs)

  model = LinearRegression()

  model.fit(X_train, y_train)

  trainScore = model.score(X_train, y_train)
  testScore = model.score(X_test, y_test)

  if testScore > trainScore and testScore >= CL:
    print(f"Test Score: {testScore} | Train Score: {trainScore} | Random State: {rs}")
    if testScore > best_test_score:
        best_test_score = testScore
        best_rs = rs

print(f"\nBest Test Score: {best_test_score} with Random State: {best_rs}")

Test Score: 0.9649618042060378 | Train Score: 0.942446542689397 | Random State: 1
Test Score: 0.9783259006626532 | Train Score: 0.9398417195515446 | Random State: 2
Test Score: 0.9560357304860488 | Train Score: 0.9473848999820091 | Random State: 4
Test Score: 0.9669763022158507 | Train Score: 0.9438505226429931 | Random State: 5
Test Score: 0.9901105113397705 | Train Score: 0.9385918220043519 | Random State: 10
Test Score: 0.9726607102794014 | Train Score: 0.9411603359254431 | Random State: 14
Test Score: 0.9633877651309604 | Train Score: 0.946138584319559 | Random State: 21
Test Score: 0.975790639498154 | Train Score: 0.9425908513252553 | Random State: 22
Test Score: 0.9687727807395896 | Train Score: 0.9464972114069966 | Random State: 24
Test Score: 0.9602561948870856 | Train Score: 0.9454518446256155 | Random State: 26
Test Score: 0.9500997612784601 | Train Score: 0.9482961316721963 | Random State: 29
Test Score: 0.9539450076685095 | Train Score: 0.9435367947390881 | Random State: 31

In [37]:
# Building the model specifically for the best test score

X_train, X_test, y_train, y_test = train_test_split(finalFeatureSet, label, test_size=0.2, random_state=10)

model = LinearRegression()

model.fit(X_train, y_train)

trainScore = model.score(X_train, y_train)
testScore = model.score(X_test, y_test)

print(f"Test Score: {np.round(testScore, 2)} | Train Score: {np.round(trainScore, 2)}")


Test Score: 0.99 | Train Score: 0.94


In [38]:
oheState.categories_[0]

array(['California', 'Florida', 'New York'], dtype=object)

In [39]:
oheState.transform(np.array([['California']]))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0.]])

In [40]:
oheState.inverse_transform(np.array([[0., 1., 0.]]))

array([['Florida']], dtype=object)

In [41]:
# Test application

rdSpend = float(input("Enter RD Spend: "))
adminSpend = float(input("Enter Admin Spend: "))
markSpend = float(input("Enter Marketing Spend: "))
state = input("Enter State: ")

#Check whether the user entered state is a valid

if state in oheState.categories_[0]:

  dummyState = oheState.transform(np.array([[state]]))

  finalFeatureInput = np.concatenate( (dummyState, np.array([[rdSpend,adminSpend,markSpend]])) , axis = 1 )

  profit = model.predict(finalFeatureInput)

  print(f"Predicted profit for your state and spending is $ {np.round(profit, 2)}")

else:
  print(f"{state} state is not recognized by the AI model !")

Enter RD Spend: 123456
Enter Admin Spend: 234567
Enter Marketing Spend: 345678
Enter State: California
Predicted profit for your state and spending is $ [[153245.46]]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [42]:
# Deploying the model and objects

import pickle

pickle.dump(model, open("ProfitPredictor.pkl", "wb"))
pickle.dump(oheState, open("StateConverter.obj", "wb"))

In [43]:
model.coef_

array([[ 8.41023126e+01,  6.95447747e+02, -7.79550060e+02,
         8.05859453e-01, -1.79706621e-02,  2.28153524e-02]])

In [44]:
model.intercept_

array([50001.73604086])